### ISSUE TITLE
Saved courses and local history in Catalog

### ISSUE THREAD

**Issue by Jdyn** [asuc-octo/berkeleytime#624]
Currently when no course is selected, there is a lot of empty space that could be filled.

## Proposition
When no course is selected, display two lists:
- Previously viewed courses on this device (Local Storage)
- Saved courses of currently logged in user

Clicking on any course in either list will take the user to the corresponding `CatalogView` in the catalog.
## Tasks
- [x] Modify the current `CatalogView` to allow the user to close the current course to return back to the lists.
- [x] Hook into the saved courses of the user and display them on the page
- [ ] Design the appearance of the layout and list design
- [ ] Implement a localStorage structure that will be saved to whenever a user views a new course
     - -[ ] The save implementation should ensure the course has not already been saved
     - -[ ] There should be a limit of maybe 20 localStorage saved courses and then begin to overwrite probably using LIFO?
